version: '3.8'

services:
  userdb:
    image: "mysql:latest"
    restart: always
    environment:
      MYSQL_DATABASE: constructxpert_user_db
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - user-db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5

  projectdb:
    image: "mysql:latest"
    restart: always
    environment:
      MYSQL_DATABASE: constructxpert_project_db
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - project-db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5

  taskdb:
    image: "mysql:latest"
    restart: always
    environment:
      MYSQL_DATABASE: constructxpert_task_db
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - task-db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5

  resourcedb:
    image: "mysql:latest"
    restart: always
    environment:
      MYSQL_DATABASE: constructxpert_resource_db
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - resource-db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - '8888:8888'
    expose:
      - '8888'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://config-server:8888/actuator/health" ]
      interval: 10s
      retries: 4

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://eureka-server:8761/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      config-server:
        condition: service_healthy

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - '8080:8080'
    expose:
      - '8080'
    environment:
      - DISCOVERY_SERVICE_URL=http://admin:admin@eureka-server:8761/eureka/
      - CONFIG_SERVICE_URL=http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:mysql://userdb:3306/constructxpert_user_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://user-service:8080/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      config-server:
        condition: service_healthy
      userdb:
        condition: service_healthy

  project-service:
    build: ./project-service
    container_name: project-service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    environment:
      - DISCOVERY_SERVICE_URL=http://admin:admin@eureka-server:8761/eureka/
      - CONFIG_SERVICE_URL=http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:mysql://projectdb:3306/constructxpert_project_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://project-service:8081/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      config-server:
        condition: service_healthy
      projectdb:
        condition: service_healthy


  task-service:
    build: ./task-service
    container_name: task-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    environment:
      - DISCOVERY_SERVICE_URL=http://admin:admin@eureka-server:8761/eureka/
      - CONFIG_SERVICE_URL=http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:mysql://taskdb:3306/constructxpert_task_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://task-service:8082/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      config-server:
        condition: service_healthy
      taskdb:
        condition: service_healthy


  resource-service:
    build: ./resource-service
    container_name: resource-service
    ports:
      - '8083:8083'
    expose:
      - '8083'
    environment:
      - DISCOVERY_SERVICE_URL=http://admin:admin@eureka-server:8761/eureka/
      - CONFIG_SERVICE_URL=http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:mysql://resourcedb:3306/constructxpert_resource_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://resource-service:8083/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      config-server:
        condition: service_healthy
      resourcedb:
        condition: service_healthy


  api-gateway-service:
    build: ./api-gateway-service
    container_name: api-gateway-service
    ports:
      - '9191:9191'
    expose:
      - '9191'
    environment:
      - DISCOVERY_SERVICE_URL=http://admin:admin@eureka-server:8761/eureka/
      - CONFIG_SERVICE_URL=http://config-server:8888
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://api-gateway-service:9191/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      config-server:
        condition: service_healthy

volumes:
  user-db:
  project-db:
  task-db:
  resource-db:
